[project]
name = "job-tracker"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.0",
	"numpy>=2.4.1",
	"python-dateutil>=2.9.0.post0",
]
